Repository FIS2425/frontend, pull requests merged in 2025-01, with the labels that each got.

#45 feat: added enable2fa component
  src/components/enable-2fa.jsx
  src/components/ui/alert.jsx
  src/components/ui/dialog.jsx
  src/services/auth.js
Labels: 😎 size/m

#55 Feat: Add Pricing Section and Finalize Homepage Content
  src/components/layouts/header.jsx
  src/pages/Landing.jsx
  src/styles/App.css
Labels: 😎 size/m

#58 Feature/31 staff profile page
  package-lock.json
  package.json
  src/App.jsx
  src/components/layouts/sidebar.jsx
  src/pages/app/Staff.jsx
  src/services/auth.js
  src/services/staff.js
Labels: 😎 size/m, 📦 Dependencies

#61 feat: substitution of suscribe buttons and addons
  src/pages/Landing.jsx
Labels: size/s

#57 Feature/38 clinic creation form
  src/App.jsx
  src/pages/app/ClinicCreation.jsx
  src/pages/app/EditClinic.jsx
  src/pages/app/PlansCreatedClinic.jsx
  src/pages/app/SuccessPage.jsx
  src/services/payments.js
Labels: 😖 size/l

#63 Feature/52 doctor list by clinic and specialty
  src/App.jsx
  src/components/layouts/sidebar.jsx
  src/pages/app/SearchStaff.jsx
  src/pages/app/Staff.jsx
  src/services/payment.js
  src/services/staff.js
  src/styles/App.css
Labels: 😎 size/m

#29 feat: create clinical history page
  src/App.jsx
  src/components/ui/badge.jsx
  src/components/ui/table.jsx
  src/pages/app/ClinicalHistory.jsx
  src/services/hystory.js
  src/styles/history.css
Labels: 😎 size/m

#64 Feature/62 Added fetch doctors in clinic view
  src/pages/app/EditClinic.jsx
Labels: 😎 size/m

#67 Feature/44 clinical history condition form
  src/App.jsx
  src/components/history.jsx
  src/forms/history/forms.jsx
  src/forms/history/schemas.jsx
  src/pages/app/ClinicalHistory.jsx
  src/services/history.js
  src/services/hystory.js
  src/utils/historyUtils.js
Labels: 😎 size/m

#56 feat(appointment): appointment views
  package-lock.json
  package.json
  src/App.jsx
  src/api/axiosClient.js
  src/components/future-appointments.jsx
  src/components/layouts/sidebar.jsx
  src/components/past-appointments.jsx
  src/components/ui/calendar.jsx
  src/components/ui/date-picker.jsx
  src/components/ui/popover.jsx
  src/components/ui/select.jsx
  src/components/ui/spinner.jsx
  src/components/ui/tabs.jsx
  src/components/weather.jsx
  src/pages/app/AppointmentDetails.jsx
  src/pages/app/Appointments.jsx
  src/services/appointment.js
  src/services/payments.js
Labels: 📦 Dependencies, 🤯 size/xl

#65 feat: add clinic actions to sidebar and update clinic editing logic
  src/components/layouts/sidebar.jsx
  src/services/payments.js
Labels: size/s

#59 Feature/34 list plans selection
  src/App.jsx
  src/pages/Plans.jsx
  src/pages/SuccessPayment.jsx
  src/services/payments.js
Labels: 😎 size/m

#75 refactor: remove unused registerPayment function from payments service
  src/services/payments.js
Labels: size/s

#76 Feature/70 clinical history treatment form
  package-lock.json
  src/components/history.jsx
  src/forms/history/forms.jsx
  src/forms/history/schemas.jsx
  src/pages/app/ClinicalHistory.jsx
  src/services/history.js
  src/utils/historyUtils.js
Labels: 😎 size/m, 📦 Dependencies

#66 Feature/39 patient creation form
  src/App.jsx
  src/components/layouts/sidebar.jsx
  src/forms/patient/forms.jsx
  src/forms/patient/schemas.js
  src/pages/app/RegisterPatient.jsx
  src/pages/app/SuccessPagePatient.jsx
  src/services/patient.js
Labels: 😎 size/m

#69 Feat(staff): errors for feature toggle supported
  src/pages/app/RegisterStaff.jsx
Labels: size/xs

#78 Feature/clinic integration sidebar
  src/App.jsx
  src/pages/app/EditClinic.jsx
  src/services/payments.js
Labels: 😎 size/m

#79 Feature/40 patient edit form
  src/App.jsx
  src/components/layouts/sidebar.jsx
  src/forms/patient/formsCreate.jsx
  src/forms/patient/formsEdit.jsx
  src/pages/app/PatientEdit.jsx
  src/pages/app/RegisterPatient.jsx
  src/services/patient.js
Labels: 😎 size/m

#80 feat: connect view from edit clinic to plan
  src/App.jsx
  src/pages/app/EditClinic.jsx
  src/services/payments.js
Labels: size/s

#82 Feature/77 clinical history files allergies form
  src/components/history.jsx
  src/forms/history/forms.jsx
  src/pages/app/ClinicalHistory.jsx
  src/services/history.js
  src/utils/historyUtils.js
Labels: 😖 size/l

#73 feat: book appointment view
  package-lock.json
  package.json
  src/App.jsx
  src/components/auth-provider.jsx
  src/components/enable-2fa.jsx
  src/components/layouts/sidebar.jsx
  src/components/ui/scroll-area.jsx
  src/pages/app/AppointmentDetails.jsx
  src/pages/app/BookAppointment.jsx
  src/pages/app/Staff.jsx
  src/services/alert.js
  src/services/appointment.js
  src/services/workshift.js
  src/utils/utils.js
Labels: 😎 size/m, 📦 Dependencies

#74 Feature/47 create workshift view
  package-lock.json
  package.json
  src/App.jsx
  src/components/appointment-card.jsx
  src/components/calendar.jsx
  src/components/layouts/sidebar.jsx
  src/components/schedule-card.jsx
  src/components/schedule-modal.jsx
  src/components/ui/date-picker-with-presets.jsx
  src/components/ui/time-picker.jsx
  src/forms/workshift/forms.jsx
  src/forms/workshift/schemas.js
  src/pages/app/DoctorSchedulePage.jsx
  src/pages/app/Home.jsx
  src/services/workshift.js
  src/utils/utils.js
Labels: 📦 Dependencies, 😖 size/l

#87 Feat(staff): sidebar updated with register a new doctor
  src/components/layouts/sidebar.jsx
  src/pages/app/RegisterStaff.jsx
Labels: size/s

#91 feat: add clinical history button in edit patient
  src/pages/app/PatientEdit.jsx
Labels: size/s
